apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oms-backend
  name: oms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms-backend
  template:
    metadata:
      labels:
        app: oms-backend
    spec:
      containers:
        - image: northamerica-northeast2-docker.pkg.dev/nt-eo-gb/nt-eo-repo/eo-oms-backend:test-latest
          name: oms-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 9011
