spring:
  datasource:
    url: jdbc:mysql://dc.inossemcanada.com:3306/oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ntdbuser
    password: Init6666
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

logging:
  level:
    #打印执行的SQL语句
    com.inossem: debug
  file:
    name: ./logs/spring.log