spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concurrent?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

logging:
  level:
    #打印执行的SQL语句
    com.test.yqq: debug
  file:
    name: ./logs/spring.log


