useInnerInterfaceCall: false
KYC:
  functions:
    validSubs: /subscription/validSubs
    getCompanyInfoByCode: /mainData/getOneByCode
server:
  port: 9011
  servlet:
    context-path: /oms

spring:
  profiles:
    active: "@spring.profiles.active@"
#    active: dev

  servlet:
    multipart.max-file-size: 100MB
    multipart.max-request-size: 1000MB
  redis:
    timeout: 6000 # 连接超时时长（毫秒）
    block-when-exhausted: true
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#mybatis-splus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.inossem.oms.base.common.domain,com.inossem.oms.base.svc.domain
  executor-type: simple
  global-config:
    db-config:
      db-type: mysql
      id-type: AUTO
      field-strategy: NOT_NULL
      logic-delete-value: -1
      logic-not-delete-value: 0
      null-value: DEFAULT
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: warning
    cache-enabled: true
    call-setters-on-nulls: true

# feign
feign:
  client:
    config:
      default:
        logger-level: full
  httpclient:
    disable-ssl-validation: true
    #enabled: false
    # okhttp:
    # enabled: true

file:
  staticAccessPath: /picture/**
  uri: /picture/

#logging:
#  level:　
#    org.springframework.aop: TRACE
